# Generated by Django 6.0.6 on 2026-08-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=100)),
                ('apellido_doctor', models.CharField(max_length=100)),
                ('cedula_doctor', models.CharField(max_length=10, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono_doctor', models.CharField(max_length=15)),
                ('correo_doctor', models.EmailField(blank=True, max_length=254)),
                ('estado_doctor', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
        ),
    ]
