# Generated by Django 6.0.6 on 2026-06-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('anio_vehiculo', models.IntegerField()),
                ('color_vehiculo', models.CharField(max_length=30)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('estado_vehiculo', models.CharField(max_length=20)),
            ],
        ),
    ]
