# Generated by Django 6.0.5 on 2026-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Pacientes', models.CharField(max_length=100)),
                ('apellido_Pacientes', models.CharField(max_length=100)),
                ('cedula_Pacientes', models.CharField(max_length=10)),
                ('telefono_Pacientes', models.CharField(max_length=15)),
                ('direccion_Pacientes', models.CharField(max_length=255)),
                ('estado_Pacientes', models.CharField(max_length=20)),
            ],
        ),
    ]
